# Generated by Django 4.2.4 on 2023-08-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('userId', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('passw', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
    ]
