# Generated by Django 4.2.4 on 2023-08-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0004_alter_vote_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin2',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
