# Generated by Django 4.2.4 on 2023-08-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0006_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin2',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('userId', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('passw', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Admin2',
            },
        ),
    ]
