# Generated by Django 4.2.4 on 2023-08-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0007_admin2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin2',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
