# Generated by Django 4.2.4 on 2023-08-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0008_delete_admin2_delete_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_politicalparties', models.CharField(max_length=50)),
                ('userId', models.EmailField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Vote',
            },
        ),
    ]
